author: flightagent
date: 2020-10-08 
version: v0.0.1
copyright: flightagent.pro@gmail.com
license: MIT
contact: flightagent.pro@gmail.com
web: flightagent.com
panel:
  name: M20-panel-radio
  position:
    x: 0
    y: 0
  labels:
    - label: 
      name: com1use
      pos: 
        x: 1
        y: 7
      dimensions:
        width: 138
        height: 52
      font:
        family: radiofont
        align: right
        size: 30px
        color: red
      decimals: 2
      indicator: com1use
    - label: 
      name: com1stb
      pos: 
        x: 167
        y: 7
      dimensions:
        width: 138
        height: 52
      font:
        color: red
        family: radiofont
        align: right
        size: 30px
      decimals: 2
      indicator: com1stb
    - label: 
      name: com2use
      pos: 
        x: 1
        y: 150
      dimensions:
        width: 137
        height: 52
      font:
        color: red
        family: radiofont
        align: right
        size: 30px
      decimals: 2
      indicator: com2use
    - label: 
      name: com2stb
      pos: 
        x: 167
        y: 150
      dimensions:
        width: 137
        height: 52
      font:
        color: red
        family: radiofont
        align: right
        size: 30px
      decimals: 2
      indicator: com2stb
    - label: 
      name: nav1use
      pos: 
        x: 350
        y: 7
      dimensions:
        width: 137
        height: 52
      font:
        color: red
        family: radiofont
        size: 30px
        align: right
      decimals: 2
      indicator: nav1use
    - label: 
      name: nav1stb
      pos: 
        x: 517
        y: 7
      dimensions:
        width: 137
        height: 52
      font:
        family: radiofont
        size: 30px
        color: red
        align: right
      decimals: 2
      indicator: nav1stb
    - label: 
      name: nav2use
      pos: 
        x: 350
        y: 150
      dimensions:
        width: 137
        height: 52
      font:
        family: radiofont
        align: right
        size: 30px
        color: red
      decimals: 2
      indicator: nav2use
    - label: 
      name: nav2stb
      pos: 
        x: 517
        y: 150
      dimensions:
        width: 137
        height: 52
      font:
        family: radiofont
        align: right
        size: 30px
        color: red
      decimals: 2
      indicator: nav2stb
    - label: 
      name: dme_nm
      pos: 
        x: 700
        y: 210
      dimensions:
        width: 34
        height: 22
      font:
        color: red
        family: arial
        size: 15px
      text: NM
    - label: 
      name: nav1dme
      pos: 
        x: 730
        y: 210
      dimensions:
        width: 66
        height: 52
      font:
        family: radiofont
        align: right
        size: 30px
        color: red
      indicator: nav1dme
    - label: 
      name: nav1spd_l
      pos: 
        x: 790
        y: 210
      dimensions:
        width: 30
        height: 22
      font:
        color: red
        family: arial
        align: right
        size: 15px
      text: KT
    - label: 
      name: nav1spd
      pos: 
        x: 810
        y: 210
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: radiofont
        align: right
        size: 30px
      indicator: nav1spd
    - label: 
      name: xpdr
      pos: 
        x: 860
        y: 120
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: radiofont
        align: right
        size: 30px
      indicator: xpdr
    - label: 
      name: adf1use
      pos: 
        x: 680
        y: 1
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: radiofont
        align: right
        size: 30px
      decimals: 1
      indicator: adf1use
    - label: 
      name: adf1stb
      pos: 
        x: 860
        y: 1
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: radiofont
        align: right
        size: 30px
      decimals: 1
      indicator: adf1stb
    - label: 
      name: ap_alt
      pos: 
        x: 300
        y: 260
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: radiofont
        size: 30px
        align: right
      indicator: ap_alt
    - label: 
      name: ap_alt_lp
      pos: 
        x: 270
        y: 270
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: arial
        size: 15px
        weight: 900
      text: ALT
    - label: 
      name: ap_alt_l
      pos: 
        x: 390
        y: 270
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: arial
        size: 15px
        weight: 900
      text: FT
    - label: 
      name: ap_fpm
      pos: 
        x: 300
        y: 290
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: radiofont
        size: 30px
        align: right
      indicator: ap_fpm
    - label: 
      name: ap_fpm_l
      pos: 
        x: 380
        y: 300
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: arial
        size: 15px
        weight: 900
      text: FPM
    - label: 
      name: ap_fpm_lp
      pos: 
        x: 270
        y: 300
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: arial
        size: 15px
        weight: 900
      text: VS
    - label: 
      name: ap_hdgl
      pos: 
        x: 80
        y: 265
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: arial
        size: 15px
        weight: 900
      text: HDG
    - label: 
      name: ap_hdg
      pos: 
        x: 120
        y: 260
      dimensions:
        width: 67
        height: 52          
      font:
        color: red
        family: radiofont
        align: right
        size: 30px
        weight: 900
      indicator: aphdg
    - label: 
      name: gear_down
      pos: 
        x: 620
        y: 300
      dimensions:
        width: 47
        height: 52          
      font:
        color: green
        family: arial
        size: 15px
        weight: 900
        align: center
      indicator: gear_down
      text: GEAR DN
    - label: 
      name: gear_unsafe
      pos: 
        x: 650
        y: 300
      dimensions:
        width: 47
        height: 52          
      font:
        color: #303030
        family: arial
        size: 15px
        weight: 900
        align: center
      indicator: gear_unsafe
      text: GEAR UNSAFE
    - label: 
      name: leftfuel_warn
      pos: 
        x: 680
        y: 300
      dimensions:
        width: 47
        height: 52          
      font:
        align: center
        color: #303030
        family: arial
        size: 15px
        weight: 900
      indicator: leftfuel
      text: LEFT FUEL
    - label: 
      name: rightfuel_warn
      pos: 
        x: 710
        y: 300
      dimensions:
        width: 47
        height: 52          
      font:
        color: #303030
        family: arial
        size: 15px
        weight: 900
        align: center
      indicator: righttfuel
      text: RIGHT FUEL