author: flightagent
date: 2020-10-08 
version: v0.0.1
copyright: flightagent.pro@gmail.com
license: MIT
contact: flightagent.pro@gmail.com
web: flightagent.com
gauges:
  - gauge: 
    name: compass
    pos: 
      x: 1902
      y: 207
    dimensions:
      width: 200
      height: 200
    foreground: compass_foreground.png
    rotationdisc:
      image: compass_disc.png
      dimensions:
          width: 719
          height: 200
      z: 20
      xmove:
        indicator: hdgmag
        minvalue: 96
        maxvalue: 816
        min: 0
        max: 719