author: flightagent
date: 2020-10-08 
version: v0.0.1
copyright: flightagent.pro@gmail.com
license: MIT
contact: flightagent.pro@gmail.com
web: flightagent.com
gauges:
  - gauge: 
    name: vsi
    background: vsi.png
    pos: 
      x: 1284
      y: 341
    dimensions:
      width: 254
      height: 254
    rotationdisc:
      image: needle_left.png
      z: 20
      min: -178
      minvalue: -2070
      max: 178 
      maxvalue: 2070
      polynomial:
        #https://elsenaju.eu/Calculator/online-curve-fit.htm
        #f(x)=-0.49091+0.06999⋅x+0.00001⋅x2
        #f(x)=-0.00000+0.08430⋅x+0.00000⋅x2
        active: true
        a0: -0.0
        a1: 0.08483
        a2: 0.0
      indicator: vsi
      units: f/m
