author: flightagent
date: 2020-10-08 
version: v0.0.1
copyright: flightagent.pro@gmail.com
license: MIT
contact: flightagent.pro@gmail.com
web: flightagent.com
gauges:
  - gauge: 
    name: turncoordinator
    background: turncordinator.png
    foreground: off.png
    foregroundnotindicator: master
    pos: 
      x: 468
      y: 334
    dimensions:
      width: 253
      height: 253
    rotationdisc:
      image: turncordinator_plane.png
      z: 130
      min: -34
      minvalue: -5.425
      max: 34
      maxvalue: 5.425
      indicator: turnind
      ccw: false
  - gauge: 
    name: turncoordinator_ball
    refobject: turncoordinator
    rotationdisc:
      image: turncordinator_slide.png
      z: 120
      min: -20
      minvalue: -117
      max: 20
      maxvalue: 117
      ccw: true
      pos:
        x: 127
        y: -20
      indicator: turnball
