author: flightagent
date: 2020-10-08 
version: v0.0.1
copyright: flightagent.pro@gmail.com
license: MIT
contact: flightagent.pro@gmail.com
web: flightagent.com
gauges:
  - gauge: 
    name: M20-oil-pressure
    background: oil_press.png
    foreground: foreground_small.png
    pos: 
      x: 177
      y: 178
    dimensions:
      width: 140
      height: 92
    rotationdisc:
      image: needle_small.png
      z: 20
      min: 5
      minvalue: 0
      max: 75 
      maxvalue: 100 
      pos:
        x: 70
        y: 92
      indicator: oilpress