author: flightagent
date: 2020-10-08 
version: v0.0.1
copyright: flightagent.pro@gmail.com
license: MIT
contact: flightagent.pro@gmail.com
web: flightagent.com
gauges:
  - gauge: 
    name: vor2
    pos: 
      x: 1621
      y: -3
    dimensions:
      width: 283
      height: 283
    background: vor_center.png
    foreground: vor_to.png
    foregroundindicator: nav2tf
    foreground2: vor_from.png
    foreground2notindicator: nav2tf
    foreground3: vor_err.png
    foreground3notindicator: nav2sgn
    rotationdisc:
      image: vor_hdg.png
      z: 20
      indicator: nav2obs
      ccw: true
      infiniterotation: true
      minvalue: 0
      maxvalue: 359.9
  - gauge: 
    name: nav2cdi
    refobject: vor2
    rotationdisc:
      image: vor_needle.png
      z: 22
      min: -30
      minvalue: -127
      max: 30
      maxvalue: 127
      pos: 
        x: 141
        y: 60
      indicator: nav2cdi
      ccw: true
