author: flightagent
date: 2020-10-08 
version: v0.0.1
copyright: flightagent.pro@gmail.com
license: MIT
contact: flightagent.pro@gmail.com
web: flightagent.com
gauges:
  - gauge:
    name: M20-leftfuel
    background: fuel_small.png
    foreground: foreground_small.png
    pos: 
      x: 18
      y: 9
    dimensions:
      width: 145
      height: 96
    rotationdisc:
      image: needle_small.png
      z: 20
      max: 80 # degress from starting position 0, starts position always 0 if nothing else indicated
      maxvalue: 100 # in percent
      pos:
        x: 72
        y: 96
      indicator: lefttank
      units: gal